FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit==1.32.0 \
    pandas==2.2.0 \
    psycopg2-binary==2.9.9 \
    sqlalchemy==2.0.27 \
    plotly==5.19.0 \
    pydeck==0.8.0

COPY dashboard/ ./dashboard/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
